/* ============================================================
   data.js — the knowledge base
   ============================================================ */

/* ---------- TODAY / SIGNALS (curated, dated) ---------- */
DATA.asOf = "2026-06-03";
DATA.digest = {
  title: "What a tech/web3 CMO should know this week",
  body: "Attention keeps fragmenting and consolidating at once: onchain consumer apps are chasing distribution through Farcaster + Base, while the strongest web2 brands keep winning by owning a distinctive voice rather than buying reach. Below: the signals worth your time, scored by how much they should change what you do.",
};
DATA.signals = [
  {c:"web3", icon:"🎩", score:92, hot:true, title:"Memecoin launchpads became the top-of-funnel for crypto",
    body:"pump.fun-style fair launches turned token creation into a content format. Attention, not product, is the first asset. The lesson isn't 'launch a coin' — it's that <b>distribution is now a game of memetic velocity</b>: a brand that can manufacture shareable moments beats one that buys impressions.",
    tags:["Memetics","Distribution","Launch"]},
  {c:"web3", icon:"🐧", score:88, title:"Pudgy Penguins keeps proving IP > hype",
    body:"A failing NFT project became a top consumer brand by going the opposite direction of crypto: physical toys in Walmart/Target, licensing, a warm brand voice. <b>Own the character, license everywhere, let the token be a community layer — not the pitch.</b>",
    tags:["Brand","IP","Licensing"]},
  {c:"web2", icon:"🦆", score:85, title:"Unhinged-but-on-strategy social is now table stakes",
    body:"Duolingo, Ryanair, and challenger brands prove a distinctive, slightly chaotic brand character drives earned reach for ~$0. The trap: chaos without a brand spine reads as desperate. <b>Character must ladder back to a real positioning.</b>",
    tags:["Social","Brand voice","Earned"]},
  {c:"web2", icon:"🤖", score:90, hot:true, title:"AI products win on product-led loops, not ad spend",
    body:"ChatGPT, Perplexity, Cursor, Midjourney scaled on word-of-mouth, sharable outputs, and Discord/community — not paid acquisition. <b>The creative IS the product output.</b> Make every use produce a shareable artifact and you turn users into a media channel.",
    tags:["AI","PLG","Loops"]},
  {c:"web3", icon:"🟦", score:84, title:"'Onchain' as a consumer wedge: Base + Farcaster Frames",
    body:"Coinbase's Base bet that consumer crypto needs cheap, fast, app-like UX. Farcaster Frames made onchain actions happen inside the social feed. <b>Reduce the steps between attention and action to zero</b> — the closer the CTA sits to the content, the higher the conversion.",
    tags:["Onchain","Social","UX"]},
  {c:"web2", icon:"🎰", score:80, title:"Betting/fantasy CAC wars push brands toward creators",
    body:"DraftKings/FanDuel maxed out promo-driven acquisition; the next edge is creator-led trust (PrizePicks, Underdog, Sleeper lean on personalities & parlay culture). <b>When everyone discounts, the moat is a community and a voice, not a bigger bonus.</b>",
    tags:["Betting","Creators","Retention"]},
  {c:"web3", icon:"🪂", score:72, title:"Airdrop/points fatigue is real — design for after the farm",
    body:"Points programs still pull liquidity and users, but mercenary capital leaves the day rewards stop. <b>The metric that matters is retention post-incentive.</b> Bake in identity, status, and habit before the airdrop, not after.",
    tags:["Tokenomics","Airdrop","Retention"]},
  {c:"web2", icon:"💀", score:78, title:"Liquid Death's playbook keeps getting copied (badly)",
    body:"Selling water to people who don't drink water by being an entertainment brand first. Copycats take the irreverence but miss the discipline: relentless consistency, merch as media, and a product that's genuinely easy to share. <b>Marketing as the product.</b>",
    tags:["Brand","DTC","Merch"]},
];

/* ---------- LEARN: curriculum modules ---------- */
DATA.modules = [
  /* --- foundations (both) --- */
  {c:"all", num:"00", track:"Foundations", title:"Positioning before promotion",
    blurb:"You can't market what you can't position. The frame that makes everything else cheaper.",
    points:[
      "<b>Positioning</b> = the context you choose so your strengths look obvious (April Dunford, <i>Obviously Awesome</i>).",
      "Define the <b>competitive alternative</b>, your unique attributes, the <b>value</b> those enable, and <b>who</b> cares most.",
      "In web3 the alternative is often 'doing nothing onchain' — you're selling a behavior change, not just a product."
    ],
    detail:{
      what:"Positioning is the deliberate act of placing your product in a context where its strengths are undeniable. Get it wrong and every dollar of promotion works against friction. Get it right and word-of-mouth does your job.",
      sections:[
        {h:"The Dunford method", b:["List the <b>competitive alternatives</b> a customer would use if you didn't exist.","Isolate the <b>attributes</b> you have that they don't.","Translate attributes into <b>value</b> (the 'so what').","Identify the <b>segment</b> that values that most — that's your beachhead.","Frame the <b>market category</b> that makes your value obvious."]},
        {h:"Web3 nuance", b:["Your true competitor is usually <b>inertia</b> + a centralized incumbent that 'just works'.","Don't lead with decentralization; lead with the <b>job</b> it does better (ownership, access, yield, speed, censorship-resistance).","'Trustless' is a feature to engineers and a red flag to normies — translate it."]},
      ],
      reading:["April Dunford — Obviously Awesome","Al Ries & Jack Trout — Positioning","Mark Ritson — on diagnosis before strategy"]
    }},
  {c:"all", num:"01", track:"Foundations", title:"Brand vs performance — the 60/40 rule",
    blurb:"The single most evidence-backed allocation in marketing. Why short-term efficiency quietly destroys growth.",
    points:[
      "Binet & Field: ~<b>60% brand, 40% activation</b> maximizes long-run profit for most businesses.",
      "Brand builds <b>future demand</b> & pricing power; activation harvests <b>existing</b> demand now.",
      "Performance dashboards over-reward activation because brand effects are slow and hard to attribute."
    ],
    detail:{
      what:"Les Binet & Peter Field's IPA analysis of hundreds of campaigns: brand building (broad, emotional, long) and sales activation (targeted, rational, short) do different jobs. Starve brand and you get a sugar high followed by rising CAC.",
      sections:[
        {h:"How to apply", b:["Split budget by <b>job</b>, not channel. A channel can do either.","Brand = reach the whole category, build memory structures, be emotional & distinctive.","Activation = reach in-market buyers with a sharp, rational offer.","Track brand with <b>share-of-search, awareness, pricing power</b>; not last-click ROAS."]},
        {h:"Startup/web3 reality", b:["Pre-PMF, lean activation to learn fast — but don't mistake that for a permanent strategy.","Once you have PMF, the brands that survive bear markets are the ones people <b>remember</b>.","Coinbase & Crypto.com spent on brand (Super Bowl, arenas) — the lesson is <b>fame is real but ROI demands discipline</b>."]},
      ],
      reading:["Binet & Field — The Long and the Short of It","Byron Sharp — How Brands Grow","Les Binet — Effectiveness in Context"]
    }},
  {c:"all", num:"02", track:"Foundations", title:"How brands actually grow",
    blurb:"Byron Sharp's evidence: growth comes from mental & physical availability and light buyers — not loyalty.",
    points:[
      "<b>Mental availability</b>: be easy to think of in a buying moment (distinctive assets, broad reach).",
      "<b>Physical availability</b>: be easy to find & buy (distribution, frictionless onboarding).",
      "Growth comes mostly from <b>more buyers</b>, especially light/occasional ones — not deeper loyalty."
    ],
    detail:{
      what:"How Brands Grow overturned a lot of folklore with data. Brands grow by increasing penetration (more people buying occasionally), built on distinctive assets and broad, consistent reach — not by chasing a niche of superfans.",
      sections:[
        {h:"Distinctive assets", b:["Colors, logos, characters, sounds, taglines that trigger instant recognition (Duo, the Liquid Death skull, Nike swoosh).","Be <b>consistent for years</b> — distinctiveness compounds; relaunches reset memory.","In web3, your PFP/mascot/ticker are distinctive assets — protect them."]},
        {h:"Reach > targeting (mostly)", b:["Most category buyers are light buyers you reach rarely. Narrow targeting misses them.","Penetration is the lever; loyalty mostly follows size, it doesn't create it.","Community is real value in web3 — but don't confuse a loud core with growth."]},
      ],
      reading:["Byron Sharp — How Brands Grow 1 & 2","Ehrenberg-Bass Institute — laws of growth"]
    }},
  {c:"all", num:"03", track:"Foundations", title:"Funnels, loops & the growth model",
    blurb:"AARRR, growth loops vs funnels, and finding the one input that moves the system.",
    points:[
      "Pirate metrics — <b>A</b>cquisition, <b>A</b>ctivation, <b>R</b>etention, <b>R</b>eferral, <b>R</b>evenue.",
      "<b>Loops > funnels</b>: the output of using the product feeds the next user's acquisition.",
      "Find your <b>growth model</b>: the equation that connects inputs to your North Star."
    ],
    detail:{
      what:"Funnels describe a one-way journey; growth loops are self-reinforcing systems where users generate more users. The best modern growth (Figma, Notion, ChatGPT, Farcaster) runs on loops.",
      sections:[
        {h:"Loop types", b:["<b>Content loops</b>: users create content that gets indexed/shared and pulls in new users (UGC, Spotify Wrapped).","<b>Viral loops</b>: usage invites others (multiplayer, referrals, invites).","<b>Paid loops</b>: revenue funds acquisition at a profitable LTV:CAC.","In web3, <b>token/points loops</b> add incentives — powerful but prone to mercenary leakage."]},
        {h:"Diagnose first", b:["Find the <b>leakiest step</b> (often activation/retention, rarely top-of-funnel).","Pick <b>one North Star</b> that proxies delivered value.","Retention is the foundation — without it, acquisition is a bucket with a hole."]},
      ],
      reading:["Brian Balfour / Reforge — Growth Loops","Andrew Chen — The Cold Start Problem","Lenny Rachitsky — growth essays"]
    }},
  {c:"all", num:"04", track:"Foundations", title:"Behavioral science & the psychology of choice",
    blurb:"Rory Sutherland & Cialdini: people don't buy logically. Design for the irrational human.",
    points:[
      "Cialdini's levers: <b>reciprocity, commitment, social proof, authority, liking, scarcity, unity</b>.",
      "Sutherland: the <b>perceived</b> value can be engineered more cheaply than the real one.",
      "Defaults, framing, and friction shape behavior more than persuasion does."
    ],
    detail:{
      what:"Most decisions are made fast and emotionally, then rationalized. Great marketing engineers context, defaults, and signals rather than arguing with the rational mind.",
      sections:[
        {h:"Practical levers", b:["<b>Social proof</b>: show usage, holders, TVL, '#1 on…'. In web3, onchain proof is native and credible.","<b>Scarcity & status</b>: allowlists, limited mints, tiers — powerful but corrosive if faked.","<b>Reciprocity</b>: give value first (free tools, airdrops, education) before asking.","<b>Defaults & friction</b>: remove steps to action; add friction to churn."]},
        {h:"Ethics line", b:["Persuasion that helps people do what they already want = good marketing.","Manufactured FOMO around financial products = regulatory and reputational landmine.","In crypto especially: <b>never imply guaranteed returns.</b>"]},
      ],
      reading:["Robert Cialdini — Influence / Pre-Suasion","Rory Sutherland — Alchemy","Kahneman — Thinking, Fast and Slow"]
    }},
  /* --- web3 track --- */
  {c:"web3", num:"W1", track:"Web3 channel", title:"Community-first growth (Discord, TG, X)",
    blurb:"In web3 the community is the product's distribution, support, and moat — built before launch.",
    points:[
      "Pre-launch community is the norm: <b>Discord/Telegram as the home, X as the megaphone</b>.",
      "Roles, allowlists, and ranks turn participation into <b>status</b> (the real currency).",
      "Mods & culture matter more than ads — a toxic or dead chat kills a token faster than a bad chart."
    ],
    detail:{
      what:"Web3 inverts the funnel: you gather a believing community first, then ship to them. The community provides liquidity, defense in FUD, content, and word-of-mouth that money can't buy.",
      sections:[
        {h:"Build it", b:["Give a <b>reason to gather</b> beyond price — a mission, an enemy, a shared identity.","Use roles/levels (Collab.Land, Guild.xyz) so contribution = visible status.","Seed <b>rituals</b>: GMs, spaces, weekly updates, alpha drops — predictability builds trust.","Recruit <b>mods from the community</b>; culture is set by who you reward."]},
        {h:"Failure modes", b:["Buying a community via airdrop farmers = mercenaries who leave.","Over-moderating kills the meme energy; under-moderating invites scammers.","Going quiet in a bear market = death. <b>Consistency is the strategy.</b>"]},
      ],
      reading:["punk6529 — Open Metaverse threads","BAYC & Pudgy community case studies","Li Jin — ownership economy"]
    }},
  {c:"web3", num:"W2", track:"Web3 channel", title:"Tokenomics & incentives as marketing",
    blurb:"Airdrops, points, and emissions are growth tools. Used well they're flywheels; used badly, ponzis.",
    points:[
      "<b>Retroactive airdrops</b> (Uniswap, ENS) reward real past usage — the cleanest playbook.",
      "<b>Points meta</b> (Blur, friend.tech, L2s) gamifies pre-token activity but invites farming.",
      "Design for <b>what happens after rewards stop</b> — incentives bootstrap, they don't retain."
    ],
    detail:{
      what:"Tokens let you pay users to bootstrap a network before it's valuable — solving the cold-start problem. The art is converting incentivized activity into genuine habit before the subsidy ends.",
      sections:[
        {h:"Playbooks", b:["<b>Retroactive airdrop</b>: reward authentic past behavior; sets a norm of 'use first, maybe rewarded later'.","<b>Points</b>: visible, gamified, flexible — but train users to chase points, not product.","<b>Liquidity mining</b>: deep but mercenary; pair with non-financial stickiness.","<b>Vampire attacks</b> (Blur vs OpenSea): target a competitor's users with superior incentives + UX."]},
        {h:"Guardrails", b:["<b>Sybil resistance</b> matters — farmers will multiply wallets.","Model the <b>post-incentive cliff</b>; many tokens dump the moment rewards end.","Don't let the token <i>be</i> the product. Solve a real job; let the token amplify it."]},
      ],
      reading:["Uniswap UNI airdrop post-mortems","Blur vs OpenSea analyses","a16z crypto — token design"]
    }},
  {c:"web3", num:"W3", track:"Web3 channel", title:"Narrative, memetics & Crypto Twitter",
    blurb:"Attention is the scarce asset. Web3 marketing is the manufacture of belief at meme speed.",
    points:[
      "Markets move on <b>narratives</b> (DeFi summer, NFTs, AI agents, RWAs) — ride or seed one.",
      "Memes are the unit of distribution; a great ticker + image can outperform a great deck.",
      "CT (Crypto Twitter) is the trading floor of attention — KOLs, threads, Spaces, replies."
    ],
    detail:{
      what:"In an information-efficient, 24/7 market, attention precedes price and price reinforces attention. Web3 marketing is reflexive: belief becomes value becomes belief. Memetics is how belief spreads.",
      sections:[
        {h:"Operate on CT", b:["<b>Pick/seed a narrative</b> and consistently associate your brand with it.","Make assets <b>remixable</b>: tickers, templates, mascots people can meme without permission.","Use <b>KOLs</b> for reach — but disclosure & authenticity decide if it lands or backfires.","Show up in <b>replies & Spaces</b>; presence compounds. The algorithm rewards consistency."]},
        {h:"Ethics & risk", b:["Paid shills with no disclosure are a reputational time bomb (and increasingly illegal).","Hype that outruns substance = the FTX/Celsius lesson.","<b>Never promise returns.</b> Sell the technology, culture, and access."]},
      ],
      reading:["Packy McCormick — Not Boring (narrative as moat)","Cobie / UpOnly — CT culture","Murad — memecoin thesis (read critically)"]
    }},
  {c:"web3", num:"W4", track:"Web3 channel", title:"Quests, ambassadors & onchain loops",
    blurb:"Engage-to-earn, guilds, and frames: turning onchain actions into measurable growth.",
    points:[
      "Quest platforms (Galxe, Zealy, Layer3) turn onboarding into a <b>gamified checklist</b>.",
      "Ambassador/guild programs scale evangelism via local & language communities.",
      "<b>Farcaster Frames</b> collapse content→action: transact inside the social post."
    ],
    detail:{
      what:"Onchain everything is measurable, which makes growth highly instrumentable — and highly gameable. Quests, ambassadors, and frames are the tactical layer on top of community and tokens.",
      sections:[
        {h:"Tactics", b:["<b>Quests</b>: design tasks that teach real product usage, not just clicks for points.","<b>Ambassadors</b>: empower regional leaders (LatAm, SEA, Turkey, Nigeria are huge crypto markets).","<b>Frames</b>: put the mint/swap/vote one tap from the feed — minimize the path to action.","<b>IRL</b>: Token2049, ETHDenver, Devconnect side-events are where deals & trust form."]},
        {h:"Measure honestly", b:["Separate <b>farmed</b> from <b>retained</b> users in every report.","Track 30/90-day onchain retention, not just quest completions.","Wallet count ≠ humans. Always."]},
      ],
      reading:["Galxe / Layer3 case studies","Farcaster Frames docs & examples","Solana/Optimism quest retrospectives"]
    }},
  {c:"web3", num:"W5", track:"Web3 channel", title:"Trust, security & regulatory comms",
    blurb:"Post-FTX, trust is the category's bottleneck. Your comms either build it or detonate it.",
    points:[
      "<b>Proof of reserves</b>, audits, and transparency are now baseline marketing, not nice-to-haves.",
      "Geo-restrictions & disclaimers protect you — bake compliance into the message.",
      "In a crisis, <b>speed + candor</b> beat silence; the community remembers how you behaved."
    ],
    detail:{
      what:"Crypto's biggest marketing problem is industry-wide distrust earned by scams and blowups. Brands that lead with transparency and security inherit the trust competitors squander.",
      sections:[
        {h:"Build trust", b:["Publish audits, reserves, and clear risk language — make it <b>legible to normies</b>.","Coinbase's regulatory-first posture is itself a brand position: 'the safe one'.","Ledger/Trezor sell <b>security as identity</b> — the message is peace of mind."]},
        {h:"Crisis comms", b:["Have a plan before you need it; name a spokesperson.","Acknowledge fast, commit to specifics, over-communicate the follow-through.","Avoid legalese-only responses in the first hour — humans need a human."]},
      ],
      reading:["Coinbase regulatory posture","Post-FTX trust analyses","Ledger Connect Kit incident response (good & bad)"]
    }},
  /* --- web2 track --- */
  {c:"web2", num:"B1", track:"Web2 channel", title:"Owned media — be the publisher (Red Bull model)",
    blurb:"Stop renting attention. Build a media engine you own so distribution compounds.",
    points:[
      "Red Bull is a media company that happens to sell drinks — content is the product's halo.",
      "Owned audiences (newsletter, YouTube, community) have <b>zero marginal CAC</b> over time.",
      "Pick a <b>content-market fit</b> niche and dominate it before you broaden."
    ],
    detail:{
      what:"Paid media is a tax you pay forever; owned media is an asset that appreciates. The strongest modern brands build an audience first, then sell into it (Morning Brew, MrBeast, Glossier-from-Into-the-Gloss).",
      sections:[
        {h:"Build the engine", b:["Choose a <b>format + cadence</b> you can sustain for years.","Optimize for <b>shareability and saves</b>, not vanity views.","Convert audience → owned channels (email/community) you control, not rented platforms.","Repurpose one idea across formats (the 'content atomization' model)."]},
        {h:"For tech/AI", b:["Make the product's <b>output</b> the content (Midjourney galleries, Spotify Wrapped, Cursor demos).","Developer brands win with <b>docs, demos, and dev-rel</b> as marketing.","Build in public — the building is the content."]},
      ],
      reading:["Red Bull Media House case","Morning Brew / Alex Lieberman","Glossier — Into the Gloss → brand"]
    }},
  {c:"web2", num:"B2", track:"Web2 channel", title:"Distinctive brand voice & cultural moments",
    blurb:"Duolingo, Liquid Death, Ryanair: a character that earns reach money can't buy.",
    points:[
      "A sharp, consistent <b>brand character</b> generates earned media for ~$0.",
      "<b>Newsjacking</b> & real-time response (Old Spice, Wendy's) turn culture into reach.",
      "Voice must ladder to <b>positioning</b> — chaos without a spine is just noise."
    ],
    detail:{
      what:"Distinctiveness is the cheapest growth lever. A brand with a real point of view and a recognizable voice gets shared, quoted, and remembered — multiplying every paid impression with earned ones.",
      sections:[
        {h:"How to build voice", b:["Define a <b>character</b> (traits, enemies, vocabulary) and document it.","Empower a small, fast social team to <b>respond in real time</b> (Duo's Zaria Parvez model).","Take a <b>stance</b> — Nike/Kaepernick, Patagonia. Polarizing beats forgettable for challengers.","Tie stunts back to the <b>core value prop</b> (Liquid Death = water made entertaining)."]},
        {h:"Risk management", b:["Edginess without judgment becomes a crisis; pre-agree the lines.","Don't chase every trend — relevance to <i>your</i> brand beats relevance to the feed.","Measure earned reach & sentiment, not just likes."]},
      ],
      reading:["Duolingo social (Zaria Parvez talks)","Liquid Death — Mike Cessario","Eugene Healey — brand strategy essays"]
    }},
  {c:"web2", num:"B3", track:"Web2 channel", title:"DTC & performance marketing that survives iOS",
    blurb:"Dollar Shave Club to today: creative is the lever, and MMM is back as attribution dies.",
    points:[
      "Post-ATT, deterministic attribution broke — <b>creative volume + MMM + incrementality</b> won.",
      "Hooks in the first 2 seconds; <b>creative is now the biggest performance variable</b>.",
      "Healthy unit economics (LTV:CAC > 3, payback < 12mo) beat growth-at-all-costs."
    ],
    detail:{
      what:"Direct-to-consumer matured from 'cheap Facebook arbitrage' (Dollar Shave Club era) to a discipline of creative testing, retention, and statistical attribution. The arbitrage is gone; the craft remains.",
      sections:[
        {h:"Modern performance", b:["Treat <b>creative as the algorithm's fuel</b> — test dozens of hooks weekly.","Rebuild attribution with <b>media mix modeling + geo holdouts + incrementality tests</b>.","Own first-party data; the cookie is dead and signal loss is permanent.","Retention/lifecycle (email/SMS) is where DTC margin actually lives."]},
        {h:"The viral launch", b:["Dollar Shave Club's $4,500 video → 12k orders in 48h: <b>one sharp idea, sharply made</b>.","The video sold a <b>feeling and a clear offer</b>, not features.","You can't bottle virality, but you can make work worth sharing and ship a lot of it."]},
      ],
      reading:["Dollar Shave Club launch breakdown","Rishabh Jain / MMM resources","Andrew Chen — paid growth limits"]
    }},
  {c:"web2", num:"B4", track:"Web2 channel", title:"AI-brand marketing: product-led + sharable output",
    blurb:"OpenAI, Perplexity, Midjourney, Cursor: how the fastest-growing software ever was marketed.",
    points:[
      "Most scaled on <b>word-of-mouth + sharable artifacts</b>, with little/no early paid spend.",
      "Community (Discord), creators, and <b>'look what I made'</b> loops do the acquisition.",
      "Distribution wedge matters: ChatGPT app, Perplexity-on-mobile, Cursor-in-IDE."
    ],
    detail:{
      what:"AI products marketed themselves by making outputs that beg to be shared and embedding into existing surfaces. ChatGPT hit 100M users faster than any consumer app — mostly on earned word-of-mouth.",
      sections:[
        {h:"AI playbook", b:["<b>The output is the ad</b> — make results screenshot- and share-worthy by default.","<b>Discord/community-led</b> (Midjourney) turns power users into evangelists & co-creators.","<b>Wedge into a habit/surface</b>: editor, browser, search, phone — reduce switching cost.","<b>Founder-led narrative</b> + build-in-public earns dev and early-adopter trust.","Watch the <b>rage-bait edge</b> (Cluely) — attention is cheap, brand equity isn't."]},
        {h:"Traps", b:["Demos that don't survive contact with real use erode trust fast.","Hype cycles punish over-promising; ship reliability, market honestly.","Paid acquisition often comes <i>after</i> PMF and loops, not before."]},
      ],
      reading:["ChatGPT growth retrospectives","Midjourney community model","Perplexity / Cursor growth notes"]
    }},
];

/* ---------- CASES ---------- */
DATA.cases = [
  /* WEB3 — classics */
  {c:"web3", era:"classic", vert:"Protocol", brand:"Uniswap", year:"2020",
    title:"The retroactive airdrop that set the standard",
    tags:["Airdrop","Tokenomics","Loyalty"],
    body:"Uniswap dropped <b>400 UNI</b> to every past user with no announcement — worth thousands overnight. It rewarded real usage, not farming, and created a norm across web3: <b>use protocols early, you might be rewarded later.</b>",
    lesson:"Reward authentic past behavior, not gamed activity. A surprise gift builds more goodwill than a promised bribe.",
    detail:{what:"In Sept 2020, Uniswap distributed UNI governance tokens retroactively to ~250k addresses that had ever used the protocol. It was a gift, not a campaign — and it reframed user acquisition for the entire industry.",
      sections:[{h:"Why it worked",b:["<b>Surprise + delight</b>: no farming, no announcement — pure reciprocity.","Rewarded <b>genuine usage</b>, filtering for real users over mercenaries.","Created an industry-wide behavior: try new protocols early 'just in case'."]},
      {h:"The double edge",b:["Spawned the <b>airdrop-farming</b> industry that now games every drop.","Set expectations that can make a no-token strategy feel like a snub.","Copycats who pre-announce lose the magic and attract Sybils."]}],
      reading:["Uniswap UNI distribution announcement","Airdrop design retrospectives"]}},
  {c:"web3", era:"classic", vert:"NFT", brand:"Yuga Labs / BAYC", year:"2021",
    title:"Bored Apes: status, IP ownership & the membership model",
    tags:["NFT","Status","IP","Community"],
    body:"BAYC sold not JPEGs but <b>membership and status</b> — plus commercial IP rights to holders, who built businesses on their apes. ApeFest, exclusive drops, and celebrity holders made it the ultimate flex.",
    lesson:"Sell identity and access, then hand creative rights to your community so they market you.",
    detail:{what:"Bored Ape Yacht Club turned a PFP collection into the dominant status symbol of the 2021 cycle by combining scarcity, an exclusive members club, celebrity adoption, and — crucially — giving holders the IP rights to their apes.",
      sections:[{h:"The mechanics",b:["<b>Status & identity</b>: your PFP signaled which tribe you belonged to.","<b>IP rights to holders</b> turned owners into builders and marketers (Bored & Hungry, music, brands).","<b>Real perks</b>: ApeFest, airdrops (Mutant apes, ApeCoin, Otherdeeds)."]},
      {h:"What dimmed it",b:["IP/roadmap execution wobbles + market collapse hit hard.","Lesson: <b>status assets need continual reasons to believe</b>, or they fade with the chart."]}],
      reading:["BAYC case studies","Yuga Labs IP strategy analyses"]}},
  {c:"web3", era:"classic", vert:"Gaming", brand:"Axie Infinity", year:"2021",
    title:"Play-to-earn & the scholarship growth loop",
    tags:["P2E","Loops","Emerging markets"],
    body:"Axie built a viral loop where owners lent NFTs to 'scholars' (esp. in the Philippines) who earned real income playing. Explosive growth — then the tokenomics couldn't hold when new users slowed.",
    lesson:"Incentive loops can grow faster than anything — and collapse just as fast if value depends on new entrants.",
    detail:{what:"Axie Infinity pioneered play-to-earn at scale. Its scholarship model created a referral-like loop in emerging markets, driving millions of users — until emissions outran real demand.",
      sections:[{h:"The loop",b:["Owners lent Axie NFTs to <b>scholars</b> for a revenue share.","Scholars earned meaningful income — powerful word-of-mouth in the Philippines, Venezuela.","Growth compounded as earnings funded more NFTs."]},
      {h:"Why it broke",b:["Rewards (SLP) inflated faster than sinks; value relied on <b>new buyers</b>.","When growth slowed, the loop reversed.","Lesson: <b>design sinks and post-incentive value before scaling emissions.</b>"]}],
      reading:["Axie Infinity economic post-mortems","Naavik P2E analyses"]}},
  {c:"web3", era:"classic", vert:"Exchange", brand:"Coinbase", year:"2022",
    title:"The bouncing-QR-code Super Bowl ad",
    tags:["Brand","Viral","Performance"],
    body:"Coinbase ran a 60-second ad of just a <b>color-changing QR code</b> bouncing like the old DVD logo. It drove ~20M hits in a minute and crashed the app. Minimalism as a scroll-stopper.",
    lesson:"A single bold, interactive idea can out-perform a polished narrative — if it earns a click and you can handle the load.",
    detail:{what:"During Super Bowl LVI, Coinbase eschewed storytelling for a hypnotic bouncing QR code leading to a sign-up bonus. It went massively viral and briefly took down the app from traffic.",
      sections:[{h:"Why it worked",b:["<b>Pattern interrupt</b>: nostalgic, mysterious, demanded interaction.","Built-in <b>CTA + incentive</b> (sign-up bonus) made it performance + brand at once.","Cheap to produce, enormous earned media."]},
      {h:"The asterisk",b:["App crashed — <b>own your infrastructure before you invite the world</b>.","Cohort quality from a bonus-driven spike is often low; measure retention, not just clicks."]}],
      reading:["Coinbase QR Super Bowl breakdowns"]}},
  {c:"web3", era:"classic", vert:"Exchange", brand:"FTX / Crypto.com", year:"2021-22",
    title:"Stadium naming & celebrity blitz — the cautionary tale",
    tags:["Brand","Sponsorship","Risk"],
    body:"FTX (Tom Brady, arena naming) and Crypto.com (Matt Damon 'Fortune Favors the Brave', LA arena) spent enormously on fame. Crypto.com's ROI was widely questioned; FTX's collapse made its marketing infamous.",
    lesson:"Fame is real, but spending must be disciplined — and no amount of brand can outrun a broken or fraudulent product.",
    detail:{what:"The 2021-22 cycle saw crypto exchanges pour money into sports and celebrity marketing. The results became case studies in both the power and the peril of brand spend without substance.",
      sections:[{h:"What to take",b:["Top-of-market <b>fame buys</b> reach but at peak prices and questionable timing.","Crypto.com's Matt Damon spot became a meme for bad timing as the market turned.","FTX's downfall is the ultimate lesson: <b>marketing can't fix a fraud.</b>"]},
      {h:"Do it better",b:["Sponsorships work when they build <b>long-term distinctive memory</b> and you can sustain them.","Tie brand spend to a real product and honest unit economics.","Don't market faster than you can deliver trust."]}],
      reading:["Crypto.com / FTX marketing retrospectives"]}},
  /* WEB3 — modern */
  {c:"web3", era:"modern", vert:"NFT", brand:"Pudgy Penguins", year:"2023-25",
    title:"The turnaround: NFT → mainstream consumer IP",
    tags:["Brand","IP","Retail","Licensing"],
    body:"Bought for ~750 ETH after near-death, Luca Netz rebuilt Pudgy as a <b>warm consumer brand</b>: physical toys in Walmart & Target, licensing, friendly storytelling — the opposite of crypto-native edginess.",
    lesson:"In web3, the winning move is often to stop marketing like web3. Build beloved IP; let the token be a layer, not the pitch.",
    detail:{what:"Pudgy Penguins is the clearest case that durable web3 brands are built like consumer brands. Luca Netz took a dead NFT project and made it a mainstream IP with retail distribution.",
      sections:[{h:"The strategy",b:["<b>Physical products</b> (Pudgy Toys) put the brand in big-box retail — distribution normies actually touch.","<b>Warm, accessible</b> storytelling vs crypto's usual cynicism.","Token/onchain layer (Pudgy World, Abstract chain) <b>supports</b> the brand, not the reverse."]},
      {h:"Why it matters",b:["Proves IP + distribution beats hype + speculation for longevity.","A blueprint for bridging web3 into mainstream culture."]}],
      reading:["Luca Netz interviews","Pudgy retail strategy coverage"]}},
  {c:"web3", era:"modern", vert:"NFT Marketplace", brand:"Blur", year:"2023",
    title:"The vampire attack: points + pro-trader UX vs OpenSea",
    tags:["Points","Vampire attack","Competitive"],
    body:"Blur attacked OpenSea's dominance with a <b>points/airdrop program</b>, zero fees, and a pro-trader UX. It flipped OpenSea on volume by targeting the highest-value users with better incentives and tooling.",
    lesson:"To unseat an incumbent, over-serve their best users with superior incentives + product, not a me-too clone.",
    detail:{what:"Blur executed a textbook 'vampire attack', siphoning OpenSea's professional traders via a multi-season points program, fee structure, and a faster, data-rich interface built for whales.",
      sections:[{h:"The play",b:["<b>Points seasons</b> gamified loyalty and bidding behavior.","<b>Pro-trader UX</b>: sweep, snipe, portfolio analytics — built for the 1% of users doing most volume.","Forced OpenSea to drop fees — a strategic win on competitor margins."]},
      {h:"The cost",b:["Incentive-driven volume includes wash/mercenary activity — read metrics carefully.","Sustaining engagement after points is the hard part."]}],
      reading:["Blur vs OpenSea analyses","Vampire attack pattern (SushiSwap origin)"]}},
  {c:"web3", era:"modern", vert:"L2 / Ecosystem", brand:"Base (Coinbase)", year:"2023-25",
    title:"'Onchain Summer' and consumer crypto distribution",
    tags:["Ecosystem","Onchain","Consumer","Memecoins"],
    body:"Base leaned into culture: <b>Onchain Summer</b> events, embracing memecoins & creators, Jesse Pollak as a visible builder-leader, and tight Farcaster integration to make onchain actions feel app-native.",
    lesson:"Distribution + culture + a credible human face beats pure tech messaging. Meet users in the feed, not the whitepaper.",
    detail:{what:"Coinbase's L2 Base bet that consumer crypto needs cheap/fast UX and cultural energy. Its marketing embraced memes, creators, and social-native onchain experiences.",
      sections:[{h:"The moves",b:["<b>Onchain Summer</b>: a recurring cultural moment with artists, brands, mints.","Embraced <b>memecoin culture</b> and creators rather than fighting it.","<b>Farcaster Frames</b>: transact inside the social post — minimal path to action.","<b>Founder-led</b>: Jesse Pollak builds in public as the brand's face."]},
      {h:"Tension",b:["Memecoin embrace courts volatility and reputational risk.","Balancing 'serious infra' with 'fun onchain' is an ongoing brand tightrope."]}],
      reading:["Base Onchain Summer recaps","Jesse Pollak talks","Farcaster Frames case studies"]}},
  {c:"web3", era:"modern", vert:"Prediction Markets", brand:"Polymarket", year:"2024",
    title:"Becoming the news: prediction markets as marketing",
    tags:["PR","Narrative","Earned media"],
    body:"During the 2024 US election, Polymarket's odds were cited by major media as a real-time signal. The product <b>became the story</b> — earned coverage no ad budget could buy.",
    lesson:"If your product generates a uniquely citable signal, the press will distribute it for you. Engineer newsworthiness into the product.",
    detail:{what:"Polymarket turned its order book into a media artifact: election odds journalists and pundits quoted constantly, making the brand synonymous with 'what the market thinks'.",
      sections:[{h:"Why it worked",b:["The product output (odds) was <b>inherently newsworthy and quotable</b>.","Positioned as a <b>truth signal</b> vs noisy polls — a sharp narrative.","Earned media flywheel: coverage → users → liquidity → better signal → more coverage."]},
      {h:"Watch-outs",b:["Regulatory scrutiny follows mainstream attention fast.","Manipulation/thin-market risks can become the next headline."]}],
      reading:["Polymarket 2024 election coverage analyses"]}},
  {c:"web3", era:"modern", vert:"Social", brand:"friend.tech", year:"2023",
    title:"Keys, points & the social-financialization experiment",
    tags:["SocialFi","Points","Hype cycle"],
    body:"friend.tech let you buy 'keys' to creators' chats, with a points program fueling frenzy. Explosive launch, then activity faded — a sharp lesson in <b>incentive-driven vs durable engagement</b>.",
    lesson:"Points can manufacture a launch spike; only real utility and habit keep people after the speculation cools.",
    detail:{what:"friend.tech fused social and speculation: keys to creators traded like assets, amplified by a points meta. It captured intense attention before retention challenges set in.",
      sections:[{h:"The spark",b:["<b>Financializing social access</b> created novelty + speculation.","Points + exclusivity drove a viral land-grab.","Demonstrated appetite for onchain social."]},
      {h:"The fade",b:["When speculation cooled, <b>core engagement was thin</b>.","Lesson: bolt incentives onto a real behavior, not the other way around."]}],
      reading:["friend.tech rise-and-fall analyses","SocialFi retrospectives"]}},
  {c:"web3", era:"modern", vert:"Memecoin", brand:"BONK / WIF / pump.fun", year:"2023-25",
    title:"Community memecoins & the launchpad attention engine",
    tags:["Memetics","Community","Fair launch"],
    body:"BONK airdropped to the Solana community to re-energize it; WIF (a dog in a hat) became a brand with a Vegas Sphere billboard funded by holders; pump.fun turned token launches into a <b>content format</b>.",
    lesson:"Memecoins are pure marketing studies: distribution, community ownership, and memetic velocity with zero 'product'.",
    detail:{what:"The memecoin wave is a live lab for attention mechanics — community airdrops, holder-funded stunts, and launchpads that made creating a token a viral act.",
      sections:[{h:"Lessons in pure attention",b:["<b>BONK</b>: a community airdrop rekindled Solana morale post-FTX — narrative as morale.","<b>WIF</b>: holders crowdfunded a Sphere ad — community as marketing budget.","<b>pump.fun</b>: launches became shareable content; <b>memetic velocity</b> is the funnel."]},
      {h:"Read critically",b:["Most memecoins are zero-sum and predatory; study the <b>mechanics</b>, not the morality.","The transferable skill: manufacturing shareable moments at speed."]}],
      reading:["Solana memecoin culture analyses","WIF Sphere campaign coverage"]}},
  {c:"web3", era:"modern", vert:"Brand x Web3", brand:"Reddit Collectible Avatars", year:"2022-23",
    title:"The biggest stealth onboarding to web3",
    tags:["Mainstream","UX","Bridge"],
    body:"Reddit put NFT avatars in its app, bought with a credit card, never saying 'NFT' or 'crypto'. Tens of millions of wallets created — by <b>hiding the web3 entirely behind familiar UX.</b>",
    lesson:"To onboard normies, delete the jargon and the friction. The best web3 UX doesn't feel like web3.",
    detail:{what:"Reddit Collectible Avatars onboarded more people to onchain ownership than almost anything else by abstracting away wallets, gas, and crypto vocabulary.",
      sections:[{h:"Why it worked",b:["<b>Credit-card checkout</b>, in-app, no seed phrases — invisible web3.","Avoided scary words ('NFT', 'wallet', 'crypto').","Tapped existing identity/status behavior on Reddit."]},
      {h:"Contrast",b:["Starbucks Odyssey tried similar but later sunset it — <b>integration depth & sustained value matter</b>.","Bridging works when it serves an existing behavior, not a crypto agenda."]}],
      reading:["Reddit Avatars onboarding analyses","Starbucks Odyssey post-mortem"]}},
  /* WEB2 — classics */
  {c:"web2", era:"classic", vert:"Consumer", brand:"Nike", year:"1988-2018",
    title:"'Just Do It' to 'Dream Crazy' — brand as belief",
    tags:["Brand","Purpose","Distinctive"],
    body:"Nike sells belief, not shoes. 'Just Do It' is a 30-year distinctive asset; the 2018 Kaepernick 'Dream Crazy' ad took a polarizing stance and <b>deepened loyalty with its core</b> while driving sales and earned media.",
    lesson:"Stand for something specific. For a challenger or a leader with a clear base, polarizing beats forgettable.",
    detail:{what:"Nike is the canonical brand-building case: decades of consistent distinctive assets plus a willingness to take cultural stances that reinforce its identity.",
      sections:[{h:"The principles",b:["<b>Consistency</b>: the swoosh + 'Just Do It' held for 30+ years (mental availability).","<b>Emotion over features</b>: sell aspiration and identity.","<b>Conviction</b>: Kaepernick alienated some, galvanized many — net brand + commercial win."]},
      {h:"For your brand",b:["A stance only works if it's <b>true to the brand</b> and its audience.","Measure long-term brand equity, not the day-one backlash."]}],
      reading:["Wieden+Kennedy Nike work","Dream Crazy campaign analyses"]}},
  {c:"web2", era:"classic", vert:"Consumer", brand:"Red Bull", year:"1987-now",
    title:"The media company that sells a drink",
    tags:["Owned media","Content","Sponsorship"],
    body:"Red Bull built Red Bull Media House, Stratos (the space jump), F1 teams, and a content empire. The product is almost a byproduct of the <b>attention machine</b> it owns.",
    lesson:"Own your distribution. Build content assets so good that media and audiences come to you for free.",
    detail:{what:"Red Bull pioneered brand-as-publisher: instead of buying attention around content, it produces the content the world wants to watch, with the brand as the natural host.",
      sections:[{h:"The model",b:["<b>Owned media at scale</b> (video, events, athletes) = compounding, low-marginal-cost reach.","<b>Stratos</b>: 8M concurrent live viewers — a brand moment money can't buy on the open market.","Content-market fit: extreme sports/energy aligns perfectly with 'gives you wings'."]},
      {h:"Apply it",b:["Pick a niche you can <b>own</b> and produce relentlessly.","The asset is the audience, not any single campaign."]}],
      reading:["Red Bull Media House case","Stratos campaign breakdowns"]}},
  {c:"web2", era:"classic", vert:"DTC", brand:"Dollar Shave Club", year:"2012",
    title:"'Our Blades Are F***ing Great' — the viral DTC launch",
    tags:["DTC","Viral","Creative"],
    body:"A ~$4,500 comedy video drove <b>12,000 orders in 48 hours</b> and defined the DTC era. One sharp idea, a clear offer, and a founder with perfect comedic timing — later a $1B Unilever exit.",
    lesson:"A single, brilliantly executed creative with a clear offer can out-perform millions in media. Make work worth sharing.",
    detail:{what:"Dollar Shave Club's launch video is the archetype of creative-led growth: cheap, funny, on-message, and built around a frictionless subscription offer.",
      sections:[{h:"Why it spread",b:["<b>Sold a feeling + a clear value</b> ('a great shave for a few bucks'), not razor specs.","Comedic, confident, eminently shareable.","Tied directly to a simple subscription CTA — brand + conversion in one."]},
      {h:"The caveat",b:["Virality is a spark, not a strategy — DSC backed it with retention & ops.","The arbitrage that made early DTC cheap is gone; the craft of creative remains."]}],
      reading:["Dollar Shave Club launch case","Michael Dubin interviews"]}},
  {c:"web2", era:"classic", vert:"Consumer", brand:"Old Spice", year:"2010",
    title:"'The Man Your Man Could Smell Like' + real-time response",
    tags:["Brand voice","Real-time","Viral"],
    body:"A surreal, fast-cut spot revived a dying brand; then the team filmed <b>~180 personalized video replies</b> to fans and celebrities in real time. Reinvented social-era responsiveness.",
    lesson:"Pair a bold creative with real-time, personal engagement to turn a campaign into a participatory event.",
    detail:{what:"Old Spice took a stale brand to cultural relevance with absurdist creative and a landmark real-time video response campaign that treated social media as live performance.",
      sections:[{h:"The two-step",b:["<b>Distinctive, surreal creative</b> reset brand perception (younger, funnier).","<b>Real-time video replies</b> to fans made the audience co-stars — massive earned reach.","Repositioned to reach the <b>female purchaser</b> of men's products — smart targeting."]},
      {h:"Today's version",b:["Duolingo, Wendy's carry this real-time-voice torch.","Speed + character + a real team empowered to act."]}],
      reading:["Old Spice Response campaign case","Wieden+Kennedy work"]}},
  {c:"web2", era:"classic", vert:"Tech", brand:"Apple", year:"1984-now",
    title:"'1984', 'Think Different' & 'Shot on iPhone'",
    tags:["Brand","Positioning","UGC"],
    body:"Apple built the most valuable brand on <b>consistent positioning</b> (creativity, simplicity, rebellion) and later turned customers into the campaign with 'Shot on iPhone' UGC billboards.",
    lesson:"Decades of disciplined positioning compound. When your product makes great output, let users create the ads.",
    detail:{what:"Apple's marketing is a masterclass in consistency and category framing — from '1984' positioning it against conformity to 'Shot on iPhone' turning product output into global UGC media.",
      sections:[{h:"The throughline",b:["<b>One clear idea</b> (creative empowerment) held for 40 years.","Product as proof: 'Shot on iPhone' = the output is the ad (an AI-era lesson too).","Premium positioning sustained by brand, enabling pricing power."]},
      {h:"Transfer",b:["AI/web3 brands: make the <b>output shareable</b> and let users market you.","Consistency is a strategy most brands abandon too early."]}],
      reading:["Apple '1984' / 'Think Different' analyses","Shot on iPhone case"]}},
  {c:"web2", era:"classic", vert:"Consumer", brand:"Spotify Wrapped", year:"2016-now",
    title:"Data as a viral, annual growth loop",
    tags:["Data","Loop","UGC"],
    body:"Spotify turns its own usage data into a <b>personalized, shareable identity artifact</b> every December. Users post it everywhere — free reach, brand love, and a recurring cultural moment.",
    lesson:"Mine your data for a personalized artifact users want to share. Build a recurring loop, not a one-off.",
    detail:{what:"Wrapped converts first-party listening data into individualized stories users proudly broadcast, generating one of the year's biggest organic social moments — for free.",
      sections:[{h:"Why it compounds",b:["<b>Identity + status</b>: your taste is content about you.","<b>Recurring ritual</b> (annual) builds anticipation and habit.","Drives competitor envy (every app now wants a 'Wrapped')."]},
      {h:"Apply it",b:["What unique data can you reflect back as an artifact?","Make it <b>personal, visual, and one-tap shareable</b>."]}],
      reading:["Spotify Wrapped case studies"]}},
  /* WEB2 — modern */
  {c:"web2", era:"modern", vert:"DTC", brand:"Liquid Death", year:"2019-25",
    title:"Selling water by being an entertainment brand",
    tags:["Brand","Merch","Anti-marketing"],
    body:"Liquid Death sells canned water to people who don't buy water — via heavy-metal aesthetics, absurdist stunts, and merch people actually want. <b>Marketing is the product;</b> the water is the merch.",
    lesson:"Compete in attention, not the category. Make a boring product entertaining and your fans become your media.",
    detail:{what:"Mike Cessario built a multi-hundred-million brand by treating water like an entertainment property: shock, comedy, merch drops, and relentless consistency.",
      sections:[{h:"The strategy",b:["<b>Entertainment-first</b>: 'Murder Your Thirst' — a comedy/metal brand that sells water.","<b>Merch as media</b>: fans pay to advertise the brand.","<b>Distinctiveness</b>: the skull, the can, the voice — unmissable shelf presence.","Stunts engineered for <b>shareability</b> (sell-your-soul, celebrity bits)."]},
      {h:"Why copies fail",b:["They take the edginess, miss the <b>discipline & consistency</b>.","Irreverence must ladder to a clear product truth (water made fun)."]}],
      reading:["Mike Cessario interviews","Liquid Death brand case"]}},
  {c:"web2", era:"modern", vert:"AI", brand:"OpenAI / ChatGPT", year:"2022-25",
    title:"Fastest to 100M users — on word-of-mouth",
    tags:["AI","PLG","Word of mouth"],
    body:"ChatGPT launched as a 'research preview' with no ad budget and hit <b>100M users in two months</b>. The product's shareable, jaw-dropping outputs did the marketing; the app and API became distribution.",
    lesson:"When the product creates 'show your friends' moments, organic word-of-mouth outpaces any paid plan.",
    detail:{what:"OpenAI's ChatGPT became the fastest-growing consumer app ever almost entirely through earned word-of-mouth, then layered distribution (app, enterprise, API) on top.",
      sections:[{h:"The growth engine",b:["<b>The output is the ad</b>: people screenshot and share astonishing results.","<b>Low friction</b> to try; immediate 'wow'.","Distribution wedges: mobile app, enterprise, developer API.","Founder/lab narrative drove credibility and constant news cycles."]},
      {h:"Lessons",b:["Reliability and trust become the marketing once scale arrives.","Paid acquisition came <i>after</i> the loop, not before."]}],
      reading:["ChatGPT growth retrospectives","OpenAI go-to-market analyses"]}},
  {c:"web2", era:"modern", vert:"AI", brand:"Midjourney", year:"2022-25",
    title:"Community-led growth inside Discord",
    tags:["AI","Community","Creators"],
    body:"Midjourney scaled to huge revenue with a tiny team by running entirely <b>inside Discord</b>: every generation is public, social, and inspiring — turning users into evangelists and a living gallery into an ad.",
    lesson:"Make creation social and public. A community that shows off its output is your best, cheapest growth channel.",
    detail:{what:"Midjourney's choice to operate in Discord made image generation a communal, visible activity — users learned from each other, competed, and shared, fueling explosive organic growth.",
      sections:[{h:"Why Discord worked",b:["<b>Public generations</b> = constant inspiration + social proof.","Community <b>teaches itself</b> prompting, lowering support cost.","Output flows to X/Reddit as endless free advertising."]},
      {h:"Trade-offs",b:["Discord UX is a barrier for some — later addressed with a web app.","Community moderation and IP debates become brand issues."]}],
      reading:["Midjourney community-led growth analyses"]}},
  {c:"web2", era:"modern", vert:"AI", brand:"Cluely", year:"2025",
    title:"Rage-bait growth: attention at any cost",
    tags:["AI","Provocation","Risk"],
    body:"Cluely (Roy Lee) marketed an AI assistant with deliberately provocative, 'cheat on everything' framing and viral stunts — manufacturing controversy to dominate the feed. Effective reach, contested brand equity.",
    lesson:"Provocation buys cheap attention fast — but study where it builds a durable brand vs where it burns trust.",
    detail:{what:"Cluely is a live case in attention-maximizing, provocation-led launch marketing in the AI era — engineered controversy as a distribution strategy.",
      sections:[{h:"The mechanics",b:["<b>Deliberate provocation</b> + stunts to trigger debate and shares.","Founder-as-character driving every news cycle.","Reach achieved at a fraction of paid cost."]},
      {h:"The debate",b:["Attention ≠ brand equity; provocation can <b>cap your TAM</b> and repel enterprise.","Works best when the controversy is <i>on-message</i>; risky when it's just shock.","Study it; copy carefully."]}],
      reading:["Cluely launch coverage","Attention-economy marketing critiques"]}},
  {c:"web2", era:"modern", vert:"AI", brand:"Perplexity", year:"2023-25",
    title:"Answer-engine positioning vs the search giant",
    tags:["AI","Positioning","Distribution"],
    body:"Perplexity positioned as the <b>answer engine</b> against Google's links, won evangelists with cited, fast answers, and chased distribution via mobile, browser, and device/carrier deals.",
    lesson:"Against a giant, pick a sharp positioning wedge and fight relentlessly for distribution surfaces.",
    detail:{what:"Perplexity carved share against Google by reframing the category ('answers, not links'), building a loyal early base, and aggressively pursuing distribution partnerships.",
      sections:[{h:"The wedge",b:["<b>Category reframe</b>: 'answer engine' makes Google's links look dated.","<b>Cited answers</b> built trust with knowledge workers.","<b>Distribution obsession</b>: apps, browser, device & telecom deals."]},
      {h:"Lessons",b:["Positioning against an incumbent's weakness is leverage.","Distribution, not just product, decides AI winners."]}],
      reading:["Perplexity go-to-market analyses"]}},
  {c:"web2", era:"modern", vert:"Betting/Fantasy", brand:"DraftKings / FanDuel", year:"2018-25",
    title:"The sports-betting CAC war",
    tags:["Betting","Promos","Retention"],
    body:"Post-PASPA, DK & FD spent billions on <b>promos, bonuses, and partnerships</b> to grab share in newly-legal markets. Acquisition got brutally expensive; the edge shifted to retention, product, and responsible-gaming trust.",
    lesson:"In a land-grab, promo-led acquisition wins share but destroys margin. Build retention and brand before the subsidy ends.",
    detail:{what:"After US sports betting legalized state-by-state, DraftKings and FanDuel waged an expensive duopoly battle — a live lesson in incentive-driven acquisition and its limits.",
      sections:[{h:"The dynamics",b:["<b>'Risk-free bet' & bonus</b> offers drove sign-ups at soaring CAC.","Media/team <b>partnerships</b> for legitimacy and reach.","As markets matured, focus shifted to <b>LTV, retention, and product</b>."]},
      {h:"Cross-over to web3",b:["Mirrors token/airdrop incentive dynamics: <b>mercenary users churn when bonuses stop</b>.","Regulatory + responsible-gaming comms are now core brand work."]}],
      reading:["US sports betting market analyses","DK/FD CAC & retention reports"]}},
  {c:"web2", era:"modern", vert:"Betting/Fantasy", brand:"PrizePicks / Underdog / Sleeper", year:"2021-25",
    title:"Creator-led fantasy & parlay culture",
    tags:["Fantasy","Creators","Community"],
    body:"Newer fantasy apps grew via <b>creators, communities, and product simplicity</b> (pick-em parlays) rather than pure promo spend — turning personalities and group chats into the acquisition engine.",
    lesson:"When incumbents out-spend you, out-community them. Creators and simple, social product mechanics beat bonus wars.",
    detail:{what:"PrizePicks, Underdog, and Sleeper expanded fantasy by leaning on creator partnerships, community/social features, and approachable product formats that spread peer-to-peer.",
      sections:[{h:"The playbook",b:["<b>Creator partnerships</b> bring built-in trust and audiences.","<b>Simple, social mechanics</b> (pick'em, group leagues) are inherently viral.","Community features (Sleeper) make the product the network."]},
      {h:"Lesson",b:["Differentiate on <b>voice + community</b> when you can't win on budget.","Same principle powers web3 community growth."]}],
      reading:["Fantasy app growth analyses","Creator-led acquisition case studies"]}},
  {c:"web2", era:"modern", vert:"Tech", brand:"Figma", year:"2016-25",
    title:"Community, multiplayer & Config: PLG done right",
    tags:["PLG","Community","Events"],
    body:"Figma grew through <b>multiplayer collaboration</b> (the product invites teammates), a plugin/template community, and Config, a beloved conference that turned users into a movement.",
    lesson:"Build virality into the product (collaboration), then nurture a community and a flagship event to cement belonging.",
    detail:{what:"Figma is a model of product-led growth: the core multiplayer feature drives organic spread, while community resources and the Config conference build identity and loyalty.",
      sections:[{h:"The loops",b:["<b>Multiplayer</b>: inviting collaborators is using the product — built-in viral loop.","<b>Community</b>: plugins, templates, files create gravity and switching costs.","<b>Config</b>: an event that gives users a tribe and the brand a cultural moment."]},
      {h:"Transfer",b:["Bake sharing into the core action (web3: onchain social/frames do this).","Events + community convert users into evangelists."]}],
      reading:["Figma PLG case studies","Config conference coverage"]}},
];

/* ---------- PEOPLE ---------- */
DATA.people = [
  /* web3 */
  {c:"web3", name:"Luca Netz", handle:"@LucaNetz", color:"#7C5CFF", init:"LN", role:"CEO, Pudgy Penguins",
    why:"The clearest model for <b>turning web3 IP into a mainstream consumer brand</b> (retail toys, licensing, warm storytelling). Follow for brand-building > hype.",
    follow:["Consumer-brand thinking applied to web3","IP & licensing strategy","Founder-led brand turnaround"]},
  {c:"web3", name:"Jesse Pollak", handle:"@jessepollak", color:"#2979FF", init:"JP", role:"Creator of Base, Coinbase",
    why:"Building <b>consumer onchain distribution</b> in public. Watch how an ecosystem markets via culture, memes, creators, and Farcaster rather than whitepapers.",
    follow:["Onchain consumer distribution","Build-in-public founder marketing","Ecosystem/culture strategy"]},
  {c:"web3", name:"Packy McCormick", handle:"@packyM", color:"#00C853", init:"PM", role:"Not Boring (writer/investor)",
    why:"Master of <b>narrative as a moat</b>. His essays show how framing and storytelling create value and attention in tech & crypto.",
    follow:["Narrative & storytelling","Tech/crypto thesis writing","Owned-media as influence"]},
  {c:"web3", name:"Anatoly Yakovenko", handle:"@aeyakovenko", color:"#D500F9", init:"AY", role:"Co-founder, Solana",
    why:"Solana's <b>'Only Possible on Solana' + hackathon + culture</b> machine is a top ecosystem-marketing study. Founder voice that sets a tone.",
    follow:["Ecosystem & developer marketing","Hackathons as growth","Memetic ecosystem culture"]},
  {c:"web3", name:"punk6529", handle:"@punk6529", color:"#FF7A45", init:"6", role:"Open Metaverse / collector",
    why:"Long-form threads on <b>community, ownership, and decentralization</b> as identity. A primer on why web3 communities cohere.",
    follow:["Community & identity","Open-metaverse philosophy","Thread craft"]},
  {c:"web3", name:"Cobie", handle:"@cobie", color:"#FFAB00", init:"C", role:"UpOnly / CT veteran",
    why:"Reads <b>Crypto Twitter culture, cycles, and hype</b> with sharp skepticism. Learn what resonates and what's nonsense on CT.",
    follow:["CT culture & sentiment","Hype-cycle skepticism","Authentic voice"]},
  {c:"web3", name:"Mert Mumtaz", handle:"@0xMert_", color:"#69F0AE", init:"M", role:"CEO, Helius (Solana)",
    why:"Sharp <b>developer-relations and ecosystem advocacy</b>. Shows how technical credibility + voice builds a brand on CT.",
    follow:["Developer relations","Technical thought leadership","Ecosystem advocacy"]},
  {c:"web3", name:"Vitalik Buterin", handle:"@VitalikButerin", color:"#82B1FF", init:"VB", role:"Co-founder, Ethereum",
    why:"The original <b>founder-as-credibility</b> brand. Long-term, substance-over-hype communication that anchors an entire ecosystem's values.",
    follow:["Substance > hype comms","Long-term value narrative","Founder credibility"]},
  {c:"web3", name:"Kain Warwick", handle:"@kaiynne", color:"#EA80FC", init:"KW", role:"Founder, Synthetix / Infinex",
    why:"DeFi-native <b>incentive design and community governance</b> at scale. A practitioner of tokenomics-as-marketing.",
    follow:["Incentive & token design","DeFi community governance","Product-led token growth"]},
  /* web2 / tech */
  {c:"web2", name:"Zaria Parvez", handle:"@zariaparvez", color:"#58CC02", init:"ZP", role:"Global Social, Duolingo",
    why:"Architect of Duolingo's <b>unhinged-but-on-strategy</b> social voice. The reference for earned reach via brand character.",
    follow:["Brand voice & social","Real-time culture marketing","Mascot/character building"]},
  {c:"web2", name:"Mike Cessario", handle:"@LiquidDeath", color:"#FF1744", init:"MC", role:"Founder, Liquid Death",
    why:"Turned water into an entertainment brand. The master of <b>marketing-as-product, merch-as-media, and stunts</b>.",
    follow:["Entertainment-first branding","Merch & community as media","Shareable stunts"]},
  {c:"web2", name:"Rory Sutherland", handle:"@rorysutherland", color:"#FF7A45", init:"RS", role:"Vice Chairman, Ogilvy",
    why:"The voice of <b>behavioral science in marketing</b>. 'Alchemy' reframes how perceived value is engineered. Essential mental models.",
    follow:["Behavioral economics","Perceived-value engineering","Counter-intuitive strategy"]},
  {c:"web2", name:"April Dunford", handle:"@aprildunford", color:"#6A45F5", init:"AD", role:"Positioning expert",
    why:"The definitive practitioner of <b>positioning</b>. 'Obviously Awesome' is the toolkit every tech/web3 marketer should run first.",
    follow:["Positioning methodology","B2B/tech go-to-market","Category framing"]},
  {c:"web2", name:"Byron Sharp", handle:"Ehrenberg-Bass", color:"#2979FF", init:"BS", role:"Author, How Brands Grow",
    why:"The <b>evidence-based laws of growth</b>: mental & physical availability, penetration over loyalty. Corrects most marketing folklore.",
    follow:["Evidence-based growth","Distinctive assets","Penetration strategy"]},
  {c:"web2", name:"Les Binet & Peter Field", handle:"IPA effectiveness", color:"#00C853", init:"BF", role:"Effectiveness researchers",
    why:"The <b>60/40 brand-vs-activation</b> evidence and 'The Long and the Short of It'. The backbone of budget strategy.",
    follow:["Brand vs activation balance","Long-term effectiveness","Measurement discipline"]},
  {c:"web2", name:"Andrew Chen", handle:"@andrewchen", color:"#FFAB00", init:"AC", role:"GP, a16z (ex-Uber growth)",
    why:"'The Cold Start Problem' and years of <b>growth-loop and network-effect</b> thinking. Bridges consumer growth and crypto networks.",
    follow:["Growth loops & networks","Cold-start strategy","Paid-growth limits"]},
  {c:"web2", name:"Lenny Rachitsky", handle:"@lennysan", color:"#D500F9", init:"LR", role:"Newsletter / ex-Airbnb",
    why:"The operating manual for <b>PLG, growth, and product marketing</b> via practitioner interviews. Best single feed for tactics.",
    follow:["PLG & growth tactics","Product marketing","Practitioner playbooks"]},
  {c:"web2", name:"Emily Weiss", handle:"@emilyweiss", color:"#EA80FC", init:"EW", role:"Founder, Glossier",
    why:"Built a brand from a <b>content community</b> (Into the Gloss → Glossier). The blueprint for community-led consumer brands.",
    follow:["Community-led brand","Content-to-commerce","Audience-first building"]},
  {c:"web2", name:"Brian Chesky", handle:"@bchesky", color:"#FF1744", init:"BC", role:"CEO, Airbnb",
    why:"Led Airbnb's pivot from performance to <b>brand & category design</b>, proving brand investment lifts even a marketplace's efficiency.",
    follow:["Brand > performance shift","Category design","Founder-led brand"]},
];

/* ---------- PLAYS (vertical playbooks) ---------- */
DATA.plays = [
  {c:"all", vert:"AI brands", icon:"🤖", color:"#7C5CFF", title:"Marketing an AI product",
    steps:[
      "<b>Make the output the ad.</b> Every use should produce a screenshot-worthy artifact people share unprompted.",
      "<b>Wedge into an existing surface/habit</b> (IDE, browser, search, phone, Discord) to minimize switching cost.",
      "<b>Community-led</b>: give power users a home (Discord/forum) where they teach each other and show off.",
      "<b>Founder-led narrative + build in public</b> earns dev and early-adopter trust and a steady news cadence.",
      "<b>Reliability is the brand</b> at scale — over-promise nothing; let demos survive real use.",
      "<b>Paid comes after loops</b>, not before. Find organic PMF first."],
    examples:["OpenAI/ChatGPT","Midjourney","Perplexity","Cursor"]},
  {c:"all", vert:"Consumer brands", icon:"🛍️", color:"#FF7A45", title:"Building a beloved consumer brand",
    steps:[
      "<b>Position sharply</b>, then commit to <b>distinctive assets</b> (color, character, sound, tagline) for years.",
      "<b>Brand character & voice</b> that earns reach — pick a stance; polarizing beats forgettable for challengers.",
      "<b>Own media</b>: become the publisher (Red Bull) so distribution compounds at low marginal cost.",
      "<b>Make sharing native</b>: merch-as-media (Liquid Death), data artifacts (Wrapped), UGC (Shot on iPhone).",
      "<b>60/40</b> brand-to-activation once you have PMF; build memory, not just clicks.",
      "<b>Physical + mental availability</b>: be easy to think of and easy to buy."],
    examples:["Nike","Liquid Death","Red Bull","Glossier","Spotify"]},
  {c:"all", vert:"Sport tech", icon:"⚽", color:"#00C853", title:"Sport tech & athlete-driven growth",
    steps:[
      "<b>Tap fandom & identity</b> — sport is tribal; align with teams, athletes, and rituals fans already love.",
      "<b>Creator/athlete partnerships</b> bring built-in trust and distribution (cheaper than broad paid).",
      "<b>Real-time + moment marketing</b>: sport is live; win the second-screen and the post-game conversation.",
      "<b>Community & second-screen product</b> (Sleeper) where the network IS the product.",
      "<b>Data & stats as content</b> — fans love numbers; turn them into shareable artifacts.",
      "<b>Sponsorship discipline</b>: buy long-term distinctive memory, not vanity logos."],
    examples:["Sleeper","Strava","Whoop","Red Bull athletes"]},
  {c:"all", vert:"Betting / Gambling / Fantasy", icon:"🎰", color:"#FFAB00", title:"Betting, gambling & fantasy",
    steps:[
      "<b>Know the land-grab trap</b>: promo-led acquisition wins share but torches margin (DK/FD CAC war).",
      "<b>Build retention & brand before the subsidy ends</b> — mercenary users churn when bonuses stop.",
      "<b>Creator-led trust</b>: personalities and parlay/community culture (PrizePicks, Underdog) out-community incumbents.",
      "<b>Simple, social product mechanics</b> (pick'em, group leagues) are inherently viral.",
      "<b>Responsible-gaming + compliance comms</b> are core brand work, not an afterthought.",
      "<b>Same dynamics as web3 incentives</b> — study airdrop/points leakage; design for post-promo habit."],
    examples:["DraftKings","FanDuel","PrizePicks","Underdog","Sleeper"]},
  {c:"web3", vert:"Token / protocol launch", icon:"🪙", color:"#7C5CFF", title:"Launching a token or protocol",
    steps:[
      "<b>Community before launch</b>: gather believers in Discord/TG/X around a mission, not just price.",
      "<b>Seed or ride a narrative</b> and consistently associate your brand with it on CT.",
      "<b>Retroactive > pre-announced</b> incentives where possible; design Sybil resistance and a post-incentive plan.",
      "<b>Memetic assets</b>: a great ticker, mascot, and remixable templates the crowd can spread freely.",
      "<b>Quests + ambassadors + frames</b> to instrument onboarding — but report farmed vs retained honestly.",
      "<b>Trust & compliance</b>: audits, transparency, geo-disclaimers; never promise returns."],
    examples:["Uniswap airdrop","Base","BONK","Blur"]},
];

/* ---------- REVIEW (critic agent stamp) ---------- */
DATA.review = {
  note:"Every entry in this hub was pressure-tested by the Critic agent against four tests: (1) is it real and verifiable, (2) is the transferable lesson clear, (3) does it avoid hype/financial promises, (4) is it honestly labeled (e.g. cautionary cases marked as such). Signals on 'Today' are curated as of "+DATA.asOf+", not live-scraped — see the note below to wire real feeds.",
  feeds:"To make 'Today' truly daily, connect a backend or scheduled job to sources like: X/Twitter lists (web3 CMOs, CT KOLs, tech founders), Farcaster channels, Polymarket, crypto news (The Block, DL News, Blockworks), product/marketing newsletters (Lenny, Not Boring, Marketing Brew), and Google Trends / share-of-search. This static build ships curated, dated signals so it's useful offline and on day one."
};
